name: Build Kernels

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
  push:
    branches:
      - mksu

jobs:
  build-a12-5-10:
    uses: ./.github/workflows/kernel-a12-5-10.yml
    secrets: inherit

  build-a13-5-10:
    uses: ./.github/workflows/kernel-a13-5-10.yml
    secrets: inherit

  build-a13-5-15:
    uses: ./.github/workflows/kernel-a13-5-15.yml
    secrets: inherit

  build-a14-5-15:
    uses: ./.github/workflows/kernel-a14-5-15.yml
    secrets: inherit

  build-a14-6-1:
    uses: ./.github/workflows/kernel-a14-6-1.yml
    secrets: inherit

  build-a15-6-6:
    uses: ./.github/workflows/kernel-a15-6-6.yml
    secrets: inherit
